[[redirects]]
	from = "/de/academy-de"
	to = "/academy"
	status = 302
	force = true
	conditions = {Language = ["en"]}

[[redirects]]
	from = "/academy"
	to = "/de/academy-de"
	status = 302
	force = true
	conditions = {Language = ["de"]}

[[redirects]]
	from = "/de"
	to = "/"
	status = 302
	force = true

[[redirects]]
	from = "/purchase-confirmation"
	to = "/bestellbestaetigung"
	status = 302
	force = true
	conditions = {Language = ["de"]}

[[redirects]]
	from = "/fieldhockey"
	to = "/"
	status = 302
	force = true

[[redirects]]
	from = "/soccer"
	to = "/"
	status = 302
	force = true

[[redirects]]
	from = "/itk"
	to = "/de/itk"
	status = 302
	force = true

[[redirects]]
	from = "/clubs"
	to = "/"
	status = 302
	force = true

[[redirects]]
	from = "/colleges"
	to = "/"
	status = 302
	force = true

