[[redirects]]
	from = "/"
	to = "/de"
	status = 302
	force = true
	conditions = {Language = ["de"]}

[[redirects]]
	from = "/de"
	to = "/"
	status = 302
	force = true
	conditions = {Language = ["en"]}

[[redirects]]
	from = "/fieldhockey"
	to = "/"
	status = 302
	force = true

[[redirects]]
	from = "/soccer"
	to = "/"
	status = 302
	force = true

[[redirects]]
	from = "/clubs"
	to = "/"
	status = 302
	force = true

[[redirects]]
	from = "/colleges"
	to = "/"
	status = 302
	force = true